// <auto-generated />
using CityInfo.API.src.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.src.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    partial class CityInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("CityInfo.API.src.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The largest city in the United States, famous for its iconic landmarks, world-class museums, and diverse neighborhoods.",
                            Name = "New York"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The second-most populous city in the United States, known for its sunny weather, entertainment industry, and cultural diversity.",
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The capital of France and one of the most beautiful cities in the world, renowned for its art, architecture, and cuisine.",
                            Name = "Paris"
                        });
                });

            modelBuilder.Entity("CityInfo.API.src.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("POIs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "A copper statue gifted to the US by France, representing liberty and freedom.",
                            Name = "Statue of Liberty"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "A 102-story skyscraper located in Midtown Manhattan, built in 1931.",
                            Name = "Empire State Building"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Description = "A large urban park located in the center of Manhattan, featuring lakes, lawns, and walking paths.",
                            Name = "Central Park"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "A world-famous landmark that overlooks the city of Los Angeles, erected in 1923.",
                            Name = "Hollywood Sign"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            Description = "A public observatory and planetarium located on the south-facing slope of Mount Hollywood.",
                            Name = "Griffith Observatory"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 2,
                            Description = "A large pier featuring an amusement park, an aquarium, restaurants, and shops.",
                            Name = "Santa Monica Pier"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 3,
                            Description = "A wrought-iron lattice tower located on the Champ de Mars in Paris, built in 1889.",
                            Name = "Eiffel Tower"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 3,
                            Description = "The world's largest art museum, featuring over 380,000 objects and 35,000 works of art.",
                            Name = "The Louvre"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 3,
                            Description = "A medieval Catholic cathedral located on the Île de la Cité in the center of Paris.",
                            Name = "Cathédrale Notre-Dame de Paris"
                        });
                });

            modelBuilder.Entity("CityInfo.API.src.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.API.src.Entities.City", "City")
                        .WithMany("POIs")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.src.Entities.City", b =>
                {
                    b.Navigation("POIs");
                });
#pragma warning restore 612, 618
        }
    }
}
